# This is the tutorial located here:
# * https://github.com/jsfenfen/irsx_cookbook

In [198]:
# importing libraries we'll use.
import csv
import os
import pandas as pd

# This tells us where the csv files are located in the system
from irsx.settings import INDEX_DIRECTORY

In [199]:
texas_np = pd.read_csv("data/eo_tx.csv")

In [200]:

# look at the first few lines
#oregon_np.head()
## print the headers as an array
list(texas_np)

['EIN',
 'NAME',
 'ICO',
 'STREET',
 'CITY',
 'STATE',
 'ZIP',
 'GROUP',
 'SUBSECTION',
 'AFFILIATION',
 'CLASSIFICATION',
 'RULING',
 'DEDUCTIBILITY',
 'FOUNDATION',
 'ACTIVITY',
 'ORGANIZATION',
 'STATUS',
 'TAX_PERIOD',
 'ASSET_CD',
 'INCOME_CD',
 'FILING_REQ_CD',
 'PF_FILING_REQ_CD',
 'ACCT_PD',
 'ASSET_AMT',
 'INCOME_AMT',
 'REVENUE_AMT',
 'NTEE_CD',
 'SORT_NAME']

In [201]:

# Ignore some columns for now
tx_np_simplified = texas_np.filter(items=['EIN', 'NAME', 'ICO', 'STREET', 'CITY', 'STATE', 'ZIP', 'INCOME_AMT', 'ASSET_AMT', 'TAX_PERIOD'])
print("total Texas orgs: %s" % len(tx_np_simplified))

# This is a toy filter for a demo -- you'd want something more robust than a perfect text match
atx_orgs = tx_np_simplified.query('CITY == "AUSTIN"')
print("total Austin, TX orgs: %s" % len(atx_orgs))

total Texas orgs: 127566
total Austin, TX orgs: 7756

In [202]:
# Show the top values by income 
atx_orgs.sort_values(by=['INCOME_AMT'], ascending=[0]).head()

,EIN,NAME,ICO,STREET,CITY,STATE,ZIP,INCOME_AMT,ASSET_AMT,TAX_PERIOD
60225,742615873,TEXAS WORKERS COMPENSATION,% TEXAS MUTUAL INSURANCE COMPANY,2200 ALDRICH STREET,AUSTIN,TX,78723-3474,6.632507e+09,7.177542e+09,201812.0
58455,742481167,SOUTHWEST KEY PROGRAMS INC,NaN,6002 JAIN LN,AUSTIN,TX,78721-3104,4.092578e+08,1.654509e+08,201808.0
25555,364336415,THE MICHAEL AND SUSAN DELL FOUNDATION,% MICH,4417 WESTLAKE DR,AUSTIN,TX,78746-1437,2.811632e+08,1.612382e+09,201812.0
59837,742587416,ELECTRIC RELIABILITY COUNCIL OF TEXAS INC 10-1...,NaN,7620 METRO CENTER DR,AUSTIN,TX,78744-1613,2.449639e+08,1.529764e+09,201812.0
50747,741109641,ST EDWARDS UNIVERSITY,% KIMBERLY KVAAL,3001 S CONGRESS AVE,AUSTIN,TX,78704-6489,2.259104e+08,3.821117e+08,201806.0

In [203]:
# this is from the index file we dowloaded at the start
pd.set_option("display.max_rows", 10)
pd.set_option('display.min_rows', 10)
INDEX_2017= os.path.join(INDEX_DIRECTORY, 'index_2017.csv')
np_2017 = pd.read_csv(INDEX_2017)
np_2017

,RETURN_ID,FILING_TYPE,EIN,TAX_PERIOD,SUB_DATE,TAXPAYER_NAME,RETURN_TYPE,DLN,OBJECT_ID
0,14054169,EFILE,42662873,201603,1/4/2017 10:27:37 AM,ELKS BUILDING CORP OF NORWOOD,990O,93493243000066,201612439349300006
1,14056200,EFILE,42964630,201512,1/4/2017 8:17:38 PM,NEIGHBORHOOD OF AFFORDABLE HOUSING INC,990,93493243000266,201612439349300026
2,14055992,EFILE,382912028,201512,1/4/2017 6:07:44 PM,RELEAF MICHIGAN INC,990,93493243003416,201612439349300341
3,14056203,EFILE,200509226,201605,1/4/2017 8:17:39 PM,ST MICHAEL ALBERTVILLE FOOTBALL BOOSTER CLUB,990,93493243005166,201612439349300516
4,14057332,EFILE,202699020,201512,1/4/2017 11:23:48 PM,KARLA SMITH FOUNDATION,990,93493243005466,201612439349300546
...,...,...,...,...,...,...,...,...,...
489008,15064384,EFILE,272948627,201512,12/29/2017 8:50:35 AM,CONSTELLA FESTIVAL OF MUSIC AND FINE ARTS,990EZ,93492320001487,201733209349200148
489009,15060607,EFILE,200745749,201512,12/28/2017 12:35:11 PM,CHRIST CHURCH INTERNATIONAL INC,990,93493319184457,201703199349318445
489010,15057955,EFILE,263520140,201608,12/27/2017 11:57:28 PM,REBELS SOCCER CLUB,990EZ,93492319074127,201723199349207412
489011,15065145,EFILE,770572762,201707,12/29/2017 12:23:10 PM,RISING FARMWORKER DREAM FUND,990PF,93491317015447,201743179349101544
489012,15063480,EFILE,481114983,201704,12/28/2017 10:23:08 PM,MADISON EDUCATIONAL ASSISTANCE FUND,990,93493319101237,201733199349310123

# Now save the list of possible filers who actually filed out to .csv

In [204]:
# Now find orgs that are in portland that filed in 2017. 
# This join requires that both fields be named EIN and be formatted the same

atx_2017_efilers = pd.merge(np_2017,
                 atx_orgs,
                 on='EIN')
print("Found a total of %s Austin 2017 efilers" % len(atx_2017_efilers))
atx_2017_efilers.head()

# sort by income amt, asset amt
atx_2017_efilers = atx_2017_efilers.sort_values(by=['INCOME_AMT', 'ASSET_AMT'], ascending=[0,0])
# Lets write them back out to a file for reference.
atx_2017_efilers.to_csv('data/atxefilers.csv')

# These are the top few for reference
atx_2017_efilers.head()

Found a total of 2046 Austin 2017 efilers

,RETURN_ID,FILING_TYPE,EIN,TAX_PERIOD_x,SUB_DATE,TAXPAYER_NAME,RETURN_TYPE,DLN,OBJECT_ID,NAME,ICO,STREET,CITY,STATE,ZIP,INCOME_AMT,ASSET_AMT,TAX_PERIOD_y
362,14179653,EFILE,742615873,201512,3/2/2017 1:11:43 PM,TEXAS MUTUAL INSURANCE COMPANY,990O,93493316016006,201603169349301600,TEXAS WORKERS COMPENSATION,% TEXAS MUTUAL INSURANCE COMPANY,2200 ALDRICH STREET,AUSTIN,TX,78723-3474,6.632507e+09,7.177542e+09,201812.0
1386,14659051,EFILE,742481167,201608,8/18/2017 9:35:04 PM,SOUTHWEST KEY PROGRAMS INC,990,93493100001117,201711009349300111,SOUTHWEST KEY PROGRAMS INC,NaN,6002 JAIN LN,AUSTIN,TX,78721-3104,4.092578e+08,1.654509e+08,201808.0
1879,14927595,EFILE,742587416,201612,11/6/2017 7:57:25 PM,ELECTRIC RELIABILITY COUNCIL OF TEXAS INC,990O,93493262007957,201702629349300795,ELECTRIC RELIABILITY COUNCIL OF TEXAS INC 10-1...,NaN,7620 METRO CENTER DR,AUSTIN,TX,78744-1613,2.449639e+08,1.529764e+09,201812.0
1594,14810761,EFILE,741109641,201606,10/6/2017 11:07:48 AM,ST EDWARDS UNIVERSITY,990,93493129006337,201731299349300633,ST EDWARDS UNIVERSITY,% KIMBERLY KVAAL,3001 S CONGRESS AVE,AUSTIN,TX,78704-6489,2.259104e+08,3.821117e+08,201806.0
1580,14775643,EFILE,454364243,201606,9/27/2017 9:40:06 AM,ASCENSION TEXAS,990,93493135124907,201701359349312490,ASCENSION HEALTH TEXAS,% TAX DEPT LANNA DOMANGUE,1345 PHILOMENA STREET,AUSTIN,TX,78723-3210,2.226907e+08,3.570680e+07,201906.0

# Dump salaries from schedule J in Austin, TX (continuing from part 1)

In [205]:
import unicodecsv as csv
from irsx.xmlrunner import XMLRunner
import pandas as pd

In [206]:

# read the whole file of orgs with efilings from part 1 here, it's not very long
file_rows = [] 
# We're using the output of part 1
with open('data/atxefilers.csv', 'rb') as infile:
    reader = csv.DictReader(infile)
    for row in reader:
        file_rows.append(row)

In [207]:
# the name of the output file
outfilename ="data/employees_simple.csv"
outfile = open(outfilename , 'wb')

# the header rows as they'll appear in the output
headers = ["period", "ein", "object_id", "taxpayer_name", "name", "business_name1", "business_name2", "title", "org_comp", "related_comp"]
# start up a dictwriter, ignore extra rows
dw = csv.DictWriter(outfile, headers, extrasaction='ignore')
dw.writeheader()

In [208]:
# get an XMLRunner -- this is what actually does the parsing
xml_runner = XMLRunner()

In [209]:
DEMO_MAX = 100
num_rows = 0

for row in file_rows:
    num_rows += 1
    this_object_id = row['OBJECT_ID']
    parsed_filing = xml_runner.run_filing(this_object_id)
    
    # if it somehow busted, just note it and continue
    if not parsed_filing:
        print("Skipping filing %s(filings with pre-2013 schemas are skipped)\n row details: %s" % (this_object_id, row))
        continue 
    
    # Is there a Schedule J there at all?
    schedule_list = parsed_filing.list_schedules()
    if 'IRS990ScheduleJ' in schedule_list:
        
        # store the output in this dict
        outputdata = {}
        # assign some initial values from the input csv
        outputdata['period'] = row['TAX_PERIOD_x']
        outputdata['ein'] = row['EIN']
        outputdata['object_id'] = row['OBJECT_ID']
        outputdata['taxpayer_name'] = row['TAXPAYER_NAME']
        
        # some schedules can appear multiple times, but schedule j only appears once
        # so we grab the first one 
        parsed_skedj = parsed_filing.get_parsed_sked('IRS990ScheduleJ')[0] 
        # now use the table name we looked up -- that's where we find it
        try:
            # repeating groups are returned as an array of dicts
            employee_groups = parsed_skedj['groups']['SkdJRltdOrgOffcrTrstKyEmpl']
        except KeyError:
            print("No SkdJRltdOrgOffcrTrstKyEmpl found in %s skipping" % this_object_id)
            continue
          
        # read through each employee and pull out the data we want
        for employee_group in employee_groups:
            
            # That leaves the following values to come from schedule J if there is one
            # "name", "business_name1", "business_name2", "title", "org_comp", "related_comp"
            # those keys come from the headers we gave dictwriter before
            outputdata['name'] = employee_group.get('PrsnNm')
            outputdata['business_name1'] = employee_group.get('BsnssNmLn1Txt')
            outputdata['business_name2'] = employee_group.get('BsnssNmLn2Txt')
            outputdata['title'] = employee_group.get('TtlTxt')
            outputdata['org_comp'] = employee_group.get('TtlCmpnstnFlngOrgAmt') # Part II Column (E) 
            outputdata['related_comp'] = employee_group.get('TtlCmpnstnRltdOrgsAmt')
        
            dw.writerow(outputdata)
        
    else:
        print("No schedule J in filing %s, skipping" % this_object_id)

    # Don't run endlessly during a demo:
    if(num_rows > DEMO_MAX):
        break
    if num_rows%100==0:
        print("Processed %s filings" % num_rows)

No schedule J in filing 201720319349301317, skipping
No schedule J in filing 201622589349301327, skipping
No schedule J in filing 201602369349300115, skipping
No schedule J in filing 201742699349300864, skipping
No schedule J in filing 201602999349300935, skipping
No schedule J in filing 201722499349300542, skipping
No schedule J in filing 201721319349305482, skipping
No schedule J in filing 201740269349300214, skipping
No schedule J in filing 201722709349300347, skipping
No schedule J in filing 201622529349300537, skipping
No schedule J in filing 201612249349302741, skipping
No schedule J in filing 201603209349104055, skipping
No schedule J in filing 201720939349300132, skipping
No schedule J in filing 201720459349301022, skipping
No schedule J in filing 201700469349301095, skipping
No schedule J in filing 201711309349303006, skipping
Processed 100 filings

In [210]:
# close the outfile
outfile.close()

pd.set_option("display.max_rows", 20)
pd.set_option('display.min_rows', 20)
sked_j_atx_efilers = pd.read_csv(outfilename)
sked_j_atx_efilers

,period,ein,object_id,taxpayer_name,name,business_name1,business_name2,title,org_comp,related_comp
0,201512,742615873,201603169349301600,TEXAS MUTUAL INSURANCE COMPANY,Richard J Gergasko,NaN,NaN,President & CEO,760251.0,0.0
1,201512,742615873,201603169349301600,TEXAS MUTUAL INSURANCE COMPANY,Perry Michael Barron,NaN,NaN,SVP & CFO,485453.0,0.0
2,201512,742615873,201603169349301600,TEXAS MUTUAL INSURANCE COMPANY,William Allen McLellan,NaN,NaN,SVP Information Technology,459291.0,0.0
3,201512,742615873,201603169349301600,TEXAS MUTUAL INSURANCE COMPANY,Terrence L Buchheit,NaN,NaN,VP Applications,479005.0,0.0
4,201512,742615873,201603169349301600,TEXAS MUTUAL INSURANCE COMPANY,Leonard Randall Johnson,NaN,NaN,SVP Investments,494329.0,0.0
5,201512,742615873,201603169349301600,TEXAS MUTUAL INSURANCE COMPANY,Mary B Nichols,NaN,NaN,General Counsel & SVP,440911.0,0.0
6,201512,742615873,201603169349301600,TEXAS MUTUAL INSURANCE COMPANY,Steven E Math,NaN,NaN,SVP Underwriting,439297.0,0.0
7,201512,742615873,201603169349301600,TEXAS MUTUAL INSURANCE COMPANY,Terry L Frakes,NaN,NaN,SVP Public Affairs,395498.0,0.0
8,201512,742615873,201603169349301600,TEXAS MUTUAL INSURANCE COMPANY,Benjamin Joel Turner,NaN,NaN,SVP & Chief Actuary,440441.0,0.0
9,201512,742615873,201603169349301600,TEXAS MUTUAL INSURANCE COMPANY,Brenda J Ward,NaN,NaN,SVP Policyholder Services,409371.0,0.0
...,...,...,...,...,...,...,...,...,...,...
473,201608,741362741,201740379349301084,TEXAS HOSPITAL ASSOCIATION,MITZI RESSMANN,NaN,NaN,"VP, MR & BUSINESS DEVELOP",187987.0,80566.0
474,201608,741362741,201740379349301084,TEXAS HOSPITAL ASSOCIATION,JENNIFER BANDA,NaN,NaN,"VP, SR. LIAISON ADV & PUBL",184222.0,0.0
475,201608,741362741,201740379349301084,TEXAS HOSPITAL ASSOCIATION,STACY WILSON,NaN,NaN,"VP, ASSOCIATE GENERAL COUN",178657.0,0.0
476,201608,741362741,201740379349301084,TEXAS HOSPITAL ASSOCIATION,RICHARD SCHIRMER,NaN,NaN,"VP, HEALTHCARE POLICY ANAL",181325.0,0.0
477,201608,741362741,201740379349301084,TEXAS HOSPITAL ASSOCIATION,ELIZABETH SJOBERG,NaN,NaN,"VP, ASSOCIATE GENERAL COUN",171254.0,0.0
478,201608,741362741,201740379349301084,TEXAS HOSPITAL ASSOCIATION,DOUGLAS LUNSFORD,NaN,NaN,"VP, STRATEGIC COMMUNICATIONS",176985.0,0.0
479,201605,746050081,201700659349300750,TEXAS INTERSCHOLASTIC LEAGUE FOUNDATION,CHARLES BREITHAUPT,NaN,NaN,DIRECTOR,0.0,329162.0
480,201609,741976051,201712269349300536,TIBH INDUSTRIES INC,FRED M WEBER JR,NaN,NaN,PRESIDENT & CEO,357232.0,NaN
481,201609,741976051,201712269349300536,TIBH INDUSTRIES INC,MARIE RICHTER,NaN,NaN,DIRECTOR OF ADMIN,166020.0,NaN
482,201609,741916289,201701159349300425,DISABILITY RIGHTS TEXAS,MARY FAITHFULL,NaN,NaN,Executive Dir.,218853.0,NaN

# Now I'm going to try and repeat this but just for the revenue streams

In [219]:

# We're creating a dictionary of all the nonprofits 
file_rows = [] 
# Essentially each row becomes an ordered dict 
with open('data/atxefilers.csv', 'rb') as infile:
    reader = csv.DictReader(infile)
    for row in reader:
        file_rows.append(row)

In [212]:
# the name of the output file
outfilename ="data/contributions_programsv_rev.csv"
outfile = open(outfilename , 'wb')

# the header rows as they'll appear in the output
headers = ["period", "ein", "object_id", "taxpayer_name", "campaigns", "membership", "fundraising", "related_orgs", "government_grants", "all_other_contributions", "non_cash_contributions", "total_contributions", "program_service_rev"]
# start up a dictwriter, ignore extra rows
dw = csv.DictWriter(outfile, headers, extrasaction='ignore')
dw.writeheader()

In [220]:
# get an XMLRunner -- this is what actually does the parsing
xml_runner = XMLRunner()

In [221]:
for row in file_rows:
    num_rows += 1
    this_object_id = row['OBJECT_ID']
    parsed_filing = xml_runner.run_filing(this_object_id)
    
    # if it somehow busted, just note it and continue
    if not parsed_filing:
        print("Skipping filing %s(filings with pre-2013 schemas are skipped)\n row details: %s" % (this_object_id, row))
        continue

In [235]:
parsed_990 = parsed_filing.get_parsed_sked('IRS990')[0]
list(parsed_990.keys())
parsed_990['schedule_parts']

{'part_0': {'object_id': '201712699349301281',
  'ein': '741109643',
  'DngBsnssAsNm_BsnssNmLn1Txt': 'Seton Healthcare Network',
  'PrncplOfcrBsnssNm_BsnssNmLn1Txt': 'Scott Herndon',
  'USAddrss_AddrssLn1Txt': '1345 Philomena Street',
  'USAddrss_CtyNm': 'Austin',
  'USAddrss_SttAbbrvtnCd': 'TX',
  'USAddrss_ZIPCd': '78723',
  'GrssRcptsAmt': '2033803591',
  'GrpRtrnFrAffltsInd': 'false',
  'GrpExmptnNm': '0928',
  'Orgnztn501c3Ind': 'X',
  'WbstAddrssTxt': 'http://www.seton.net',
  'OfOrgnztnCrpInd': 'X',
  'FrmtnYr': '1900',
  'LglDmclSttCd': 'TX'},
 'part_i': {'object_id': '201712699349301281',
  'ein': '741109643',
  'ActvtyOrMssnDsc': 'Provision of healthcare services with a special concern for the poor and vulnerable.',
  'VtngMmbrsGvrnngBdyCnt': '12',
  'VtngMmbrsIndpndntCnt': '10',
  'TtlEmplyCnt': '13208',
  'TtlVlntrsCnt': '2000',
  'TtlGrssUBIAmt': '860222',
  'NtUnrltdBsTxblIncmAmt': '-1551389',
  'PYCntrbtnsGrntsAmt': '31675532',
  'CYCntrbtnsGrntsAmt': '26656186',
  'PYPrgrmSrvcRvnAmt': '1874419067',
  'CYPrgrmSrvcRvnAmt': '1953063418',
  'PYInvstmntIncmAmt': '32406920',
  'CYInvstmntIncmAmt': '6581395',
  'PYOthrRvnAmt': '64659950',
  'CYOthrRvnAmt': '35594479',
  'PYTtlRvnAmt': '2003161469',
  'CYTtlRvnAmt': '2021895478',
  'PYGrntsAndSmlrPdAmt': '3383934',
  'CYGrntsAndSmlrPdAmt': '3340045',
  'PYBnftsPdTMmbrsAmt': '0',
  'CYBnftsPdTMmbrsAmt': '0',
  'PYSlrsCmpEmpBnftPdAmt': '821623724',
  'CYSlrsCmpEmpBnftPdAmt': '782613194',
  'PYTtlPrfFndrsngExpnsAmt': '0',
  'CYTtlPrfFndrsngExpnsAmt': '0',
  'CYTtlFndrsngExpnsAmt': '0',
  'PYOthrExpnssAmt': '841861902',
  'CYOthrExpnssAmt': '966524584',
  'PYTtlExpnssAmt': '1666869560',
  'CYTtlExpnssAmt': '1752477823',
  'PYRvnsLssExpnssAmt': '336291909',
  'CYRvnsLssExpnssAmt': '269417655',
  'TtlAsstsBOYAmt': '3131871173',
  'TtlAsstsEOYAmt': '3306001380',
  'TtlLbltsBOYAmt': '727179060',
  'TtlLbltsEOYAmt': '708931624',
  'NtAsstsOrFndBlncsBOYAmt': '2404692113',
  'NtAsstsOrFndBlncsEOYAmt': '2597069756'},
 'part_iii': {'object_id': '201712699349301281',
  'ein': '741109643',
  'MssnDsc': "Our mission inspires us to care for and improve the health of those we serve with a special concern for the sick and the poor. We are called to be a sign of God's unconditional love for all and believe that all persons by their creation are endowed with dignity. Seton continues the Catholic tradition of service established by our founders: Vincent de Paul, Louise de Marillac, and Elizabeth Ann Seton.",
  'SgnfcntNwPrgrmSrvcInd': 'false',
  'SgnfcntChngInd': 'false',
  'ExpnsAmt': '1529109843',
  'GrntAmt': '3340045',
  'RvnAmt': '1986773630',
  'Dsc': "As the leading provider of health services in Central Texas (an 11-county region), Seton Family of Hospitals (Seton) also provides a number of distinctive services to the community: the only Level I trauma facilities; the only free-standing children's hospital; the only free-standing inpatient behavioral health hospital; the only heart transplant center; and the only University of Texas medical residency programs. Seton contributes to the positive health status of the communities it serves and continues to build and strengthen sustainable collaborative efforts to benefit the health of individuals, families and society as a whole. Seton has a mission to care for the community it serves with a special concern for the poor and the vulnerable. (CONTINUED ON SCHEDULE O)",
  'TtlPrgrmSrvcExpnssAmt': '1529109843'},
 'part_iv': {'object_id': '201712699349301281',
  'ein': '741109643',
  'DscrbdInSctn501c3Ind': 'true',
  'SkdBRqrdInd': 'true',
  'PltclCmpgnActyInd': 'false',
  'LbbyngActvtsInd': 'true',
  'SbjctTPrxyTxInd': 'false',
  'DnrAdvsdFndInd': 'false',
  'CnsrvtnEsmntsInd': 'false',
  'CllctnsOfArtInd': 'false',
  'CrdtCnslngInd': 'false',
  'TmpOrPrmnntEndwmntsInd': 'true',
  'RprtLndBldngEqpmntInd': 'true',
  'RprtInvstmntsOthrScInd': 'false',
  'RprtPrgrmRltdInvstInd': 'false',
  'RprtOthrAsstsInd': 'true',
  'RprtOthrLbltsInd': 'true',
  'IncldFIN48FtntInd': 'true',
  'IndpndntAdtFnclStmtInd': 'false',
  'CnsldtdAdtFnclStmtInd': 'true',
  'SchlOprtngInd': 'false',
  'FrgnOffcInd': 'false',
  'FrgnActvtsInd': 'false',
  'MrThn5000KTOrgInd': 'false',
  'MrThn5000KTIndvdlsInd': 'false',
  'PrfssnlFndrsngInd': 'false',
  'FndrsngActvtsInd': 'false',
  'GmngActvtsInd': 'false',
  'OprtHsptlInd': 'true',
  'AdtdFnnclStmtAttInd': 'true',
  'GrntsTOrgnztnsInd': 'true',
  'GrntsTIndvdlsInd': 'true',
  'SkdJRqrdInd': 'true',
  'TxExmptBndsInd': 'false',
  'EnggdInExcssBnftTrnsInd': 'false',
  'PYExcssBnftTrnsInd': 'false',
  'LnOtstndngInd': 'false',
  'GrntTRltdPrsnInd': 'false',
  'BsnssRlnWthOrgMmInd': 'false',
  'BsnssRlnWthFmMmInd': 'false',
  'BsnssRlnWthOffcrEntInd': 'false',
  'DdctblNnCshCntrInd': 'false',
  'DdctblArtCntrbtnInd': 'false',
  'TrmntOprtnsInd': 'false',
  'PrtlLqdtnInd': 'false',
  'DsrgrddEnttyInd': 'true',
  'RltdEnttyInd': 'true',
  'RltdOrgnztnCtrlEntInd': 'true',
  'TrnsctnWthCntrlEntInd': 'true',
  'TrnsfrExmptNnChrtblRltdOrgInd': 'false',
  'ActvtsCndctdPrtshpInd': 'false',
  'SkdORqrdInd': 'true'},
 'part_v': {'object_id': '201712699349301281',
  'ein': '741109643',
  'IRPDcmntCnt': '1698',
  'IRPDcmntW2GCnt': '0',
  'BckpWthldCmplncInd': 'true',
  'EmplyCnt': '13208',
  'EmplymntTxRtrnsFldInd': 'true',
  'UnrltdBsIncmOvrLmtInd': 'true',
  'Frm990TFldInd': 'true',
  'FrgnFnnclAccntInd': 'false',
  'PrhbtdTxShltrTrnsInd': 'false',
  'TxblPrtyNtfctnInd': 'false',
  'NnddctblCntrbtnsInd': 'false',
  'QdPrQCntrbtnsInd': 'true',
  'QdPrQCntrDsclInd': 'true',
  'Frm8282PrprtyDspsdOfInd': 'false',
  'RcvFndsTPyPrsnlBnftCntrctInd': 'false',
  'PyPrmmsPrsnlBnftCntrctInd': 'false',
  'IndrTnnngSrvcsInd': 'false'},
 'part_vi': {'object_id': '201712699349301281',
  'ein': '741109643',
  'InfInSkdOPrtVIInd': 'X',
  'GvrnngBdyVtngMmbrsCnt': '12',
  'IndpndntVtngMmbrCnt': '10',
  'FmlyOrBsnssRlnInd': 'false',
  'DlgtnOfMgmtDtsInd': 'false',
  'ChngTOrgDcmntsInd': 'false',
  'MtrlDvrsnOrMssInd': 'false',
  'MmbrsOrStckhldrsInd': 'true',
  'ElctnOfBrdMmbrsInd': 'true',
  'DcsnsSbjctTApprvInd': 'true',
  'MntsOfGvrnngBdyInd': 'true',
  'MntsOfCmmttsInd': 'true',
  'OffcrMlngAddrssInd': 'false',
  'LclChptrsInd': 'false',
  'Frm990PrvddTGvrnBdyInd': 'false',
  'CnflctOfIntrstPlcyInd': 'true',
  'AnnlDsclsrCvrdPrsnInd': 'true',
  'RglrMntrngEnfrcInd': 'true',
  'WhstlblwrPlcyInd': 'true',
  'DcmntRtntnPlcyInd': 'true',
  'CmpnstnPrcssCEOInd': 'false',
  'CmpnstnPrcssOthrInd': 'false',
  'InvstmntInJntVntrInd': 'true',
  'WrttnPlcyOrPrcdrInd': 'true',
  'UpnRqstInd': 'X',
  'BsnssNm_BsnssNmLn1Txt': 'Scott Herndon',
  'BksInCrOfDtl_PhnNm': '5123241000',
  'USAddrss_AddrssLn1Txt': '1345 Philomena Street',
  'USAddrss_CtyNm': 'Austin',
  'USAddrss_SttAbbrvtnCd': 'TX',
  'USAddrss_ZIPCd': '78723'},
 'part_vii': {'object_id': '201712699349301281',
  'ein': '741109643',
  'TtlRprtblCmpFrmOrgAmt': '19647125',
  'TtRprtblCmpRltdOrgAmt': '0',
  'TtlOthrCmpnstnAmt': '692569',
  'IndvRcvdGrtrThn100KCnt': '707',
  'FrmrOfcrEmplysLstdInd': 'true',
  'TtlCmpGrtrThn150KInd': 'true',
  'CmpnstnFrmOthrSrcsInd': 'false',
  'CntrctRcvdGrtrThn100KCnt': '135'},
 'part_viii': {'object_id': '201712699349301281',
  'ein': '741109643',
  'InfInSkdOPrtVIIIInd': 'X',
  'RltdOrgnztnsAmt': '19277811',
  'GvrnmntGrntsAmt': '4794351',
  'AllOthrCntrbtnsAmt': '2584024',
  'TtlCntrbtnsAmt': '26656186',
  'TtlOthPrgrmSrvcRv_TtlRvnClmnAmt': '3957898',
  'TtlOthPrgrmSrvcRv_RltdOrExmptFncIncmAmt': '3270942',
  'TtlOthPrgrmSrvcRv_UnrltdBsnssRvnAmt': '686956',
  'TtlOthPrgrmSrvcRv_ExclsnAmt': '0',
  'TtlPrgrmSrvcRvnAmt': '1953063418',
  'InvstmntIncm_TtlRvnClmnAmt': '6547915',
  'InvstmntIncm_ExclsnAmt': '6547915',
  'GrssRnts_RlAmt': '3214497',
  'RntlIncmOrLss_RlAmt': '3214497',
  'RntlIncmOrLss_PrsnlAmt': '0',
  'NtRntlIncmOrLss_TtlRvnClmnAmt': '3214497',
  'NtRntlIncmOrLss_ExclsnAmt': '3214497',
  'GrssAmntSlsAssts_OthrAmt': '33480',
  'GnOrLss_ScrtsAmt': '0',
  'GnOrLss_OthrAmt': '33480',
  'NtGnOrLssInvstmnts_TtlRvnClmnAmt': '33480',
  'NtGnOrLssInvstmnts_ExclsnAmt': '33480',
  'FndrsngDrctExpnssAmt': '11908113',
  'NtIncmFrmFndrsngEvt_TtlRvnClmnAmt': '-11908113',
  'NtIncmFrmFndrsngEvt_ExclsnAmt': '-11908113',
  'MscRvn_TtlRvnClmnAmt': '34807984',
  'MscRvn_RltdOrExmptFncIncmAmt': '31306194',
  'MscRvn_UnrltdBsnssRvnAmt': '173266',
  'MscRvn_ExclsnAmt': '3328524',
  'OthrRvnTtlAmt': '44288095',
  'TtlRvn_TtlRvnClmnAmt': '2021895478',
  'TtlRvn_RltdOrExmptFncIncmAmt': '1986773630',
  'TtlRvn_UnrltdBsnssRvnAmt': '860222',
  'TtlRvn_ExclsnAmt': '7605440'},
 'part_ix': {'object_id': '201712699349301281',
  'ein': '741109643',
  'InfInSkdOPrtIXInd': 'X',
  'GrntsTDmstcOrgs_TtlAmt': '3196045',
  'GrntsTDmstcOrgs_PrgrmSrvcsAmt': '3196045',
  'GrntsTDmstcIndvdls_TtlAmt': '144000',
  'GrntsTDmstcIndvdls_PrgrmSrvcsAmt': '144000',
  'CmpCrrntOfcrDrctrs_TtlAmt': '18354857',
  'CmpCrrntOfcrDrctrs_PrgrmSrvcsAmt': '18354857',
  'CmpDsqlPrsns_TtlAmt': '1835577',
  'CmpDsqlPrsns_PrgrmSrvcsAmt': '1835577',
  'OthrSlrsAndWgs_TtlAmt': '613444368',
  'OthrSlrsAndWgs_PrgrmSrvcsAmt': '532736140',
  'OthrSlrsAndWgs_MngmntAndGnrlAmt': '80708228',
  'OthrEmplyBnfts_TtlAmt': '106227417',
  'OthrEmplyBnfts_PrgrmSrvcsAmt': '102455806',
  'OthrEmplyBnfts_MngmntAndGnrlAmt': '3771611',
  'PyrllTxs_TtlAmt': '42750975',
  'PyrllTxs_PrgrmSrvcsAmt': '42750975',
  'FsFrSrvcsMngmnt_TtlAmt': '220686299',
  'FsFrSrvcsMngmnt_PrgrmSrvcsAmt': '168399631',
  'FsFrSrvcsMngmnt_MngmntAndGnrlAmt': '52286668',
  'FsFrSrvcsLgl_TtlAmt': '57380',
  'FsFrSrvcsLgl_PrgrmSrvcsAmt': '43785',
  'FsFrSrvcsLgl_MngmntAndGnrlAmt': '13595',
  'FsFrSrvcsAccntng_TtlAmt': '2318566',
  'FsFrSrvcsAccntng_PrgrmSrvcsAmt': '1769234',
  'FsFrSrvcsAccntng_MngmntAndGnrlAmt': '549332',
  'FsFrSrvcsLbbyng_TtlAmt': '455028',
  'FsFrSrvcsLbbyng_MngmntAndGnrlAmt': '455028',
  'FsFrSrvcsOthr_TtlAmt': '179274711',
  'FsFrSrvcsOthr_PrgrmSrvcsAmt': '137146809',
  'FsFrSrvcsOthr_MngmntAndGnrlAmt': '42127902',
  'FsFrSrvcsOthr_FndrsngAmt': '0',
  'Advrtsng_TtlAmt': '7441150',
  'Advrtsng_PrgrmSrvcsAmt': '7441150',
  'OffcExpnss_TtlAmt': '18925751',
  'OffcExpnss_PrgrmSrvcsAmt': '18925751',
  'InfrmtnTchnlgy_TtlAmt': '3666572',
  'InfrmtnTchnlgy_PrgrmSrvcsAmt': '2665077',
  'InfrmtnTchnlgy_MngmntAndGnrlAmt': '1001495',
  'Occpncy_TtlAmt': '48355343',
  'Occpncy_PrgrmSrvcsAmt': '48355343',
  'Trvl_TtlAmt': '4199175',
  'Trvl_PrgrmSrvcsAmt': '3052204',
  'Trvl_MngmntAndGnrlAmt': '1146971',
  'CnfrncsMtngs_TtlAmt': '2954170',
  'CnfrncsMtngs_PrgrmSrvcsAmt': '2147262',
  'CnfrncsMtngs_MngmntAndGnrlAmt': '806908',
  'Intrst_TtlAmt': '13076746',
  'Intrst_PrgrmSrvcsAmt': '13076746',
  'DprctnDpltn_TtlAmt': '70524217',
  'DprctnDpltn_PrgrmSrvcsAmt': '68893202',
  'DprctnDpltn_MngmntAndGnrlAmt': '1631015',
  'Insrnc_TtlAmt': '8421322',
  'Insrnc_PrgrmSrvcsAmt': '1121683',
  'Insrnc_MngmntAndGnrlAmt': '7299639',
  'AllOthrExpnss_TtlAmt': '79966764',
  'AllOthrExpnss_PrgrmSrvcsAmt': '58085146',
  'AllOthrExpnss_MngmntAndGnrlAmt': '21881618',
  'AllOthrExpnss_FndrsngAmt': '0',
  'TtlFnctnlExpnss_TtlAmt': '1752477823',
  'TtlFnctnlExpnss_PrgrmSrvcsAmt': '1529109843',
  'TtlFnctnlExpnss_MngmntAndGnrlAmt': '223367980',
  'TtlFnctnlExpnss_FndrsngAmt': '0'},
 'part_x': {'object_id': '201712699349301281',
  'ein': '741109643',
  'CshNnIntrstBrng_BOYAmt': '0',
  'CshNnIntrstBrng_EOYAmt': '0',
  'AccntsRcvbl_BOYAmt': '276053576',
  'AccntsRcvbl_EOYAmt': '251879151',
  'RcvblsFrmOffcrsEtc_EOYAmt': '0',
  'RcvblFrmDsqlfdPrsn_EOYAmt': '0',
  'InvntrsFrSlOrUs_BOYAmt': '28882634',
  'InvntrsFrSlOrUs_EOYAmt': '27962405',
  'PrpdExpnssDfrdChrgs_BOYAmt': '7045844',
  'PrpdExpnssDfrdChrgs_EOYAmt': '7666745',
  'LndBldgEqpCstOrOthrBssAmt': '1590738817',
  'LndBldgEqpAccmDprcAmt': '701881440',
  'LndBldgEqpBssNt_BOYAmt': '810180279',
  'LndBldgEqpBssNt_EOYAmt': '888857377',
  'InvstmntsOthrScrts_BOYAmt': '0',
  'InvstmntsPrgrmRltd_BOYAmt': '19336260',
  'InvstmntsPrgrmRltd_EOYAmt': '19063805',
  'IntngblAssts_BOYAmt': '30817425',
  'IntngblAssts_EOYAmt': '45292717',
  'OthrAsstsTtl_BOYAmt': '1959555155',
  'OthrAsstsTtl_EOYAmt': '2065279180',
  'TtlAssts_BOYAmt': '3131871173',
  'TtlAssts_EOYAmt': '3306001380',
  'AccntsPyblAccrExpnss_BOYAmt': '183050357',
  'AccntsPyblAccrExpnss_EOYAmt': '161777417',
  'DfrrdRvn_BOYAmt': '1277026',
  'DfrrdRvn_EOYAmt': '2716351',
  'UnscrdNtsLnsPybl_BOYAmt': '5505816',
  'UnscrdNtsLnsPybl_EOYAmt': '5723823',
  'OthrLblts_BOYAmt': '537345861',
  'OthrLblts_EOYAmt': '538714033',
  'TtlLblts_BOYAmt': '727179060',
  'TtlLblts_EOYAmt': '708931624',
  'OrgnztnFllwsSFAS117Ind': 'X',
  'UnrstrctdNtAssts_BOYAmt': '2385355853',
  'UnrstrctdNtAssts_EOYAmt': '2578005951',
  'TmprrlyRstrNtAssts_BOYAmt': '19336260',
  'TmprrlyRstrNtAssts_EOYAmt': '19063805',
  'TtlNtAsstsFndBlnc_BOYAmt': '2404692113',
  'TtlNtAsstsFndBlnc_EOYAmt': '2597069756',
  'TtLbNtAsstsFndBlnc_BOYAmt': '3131871173',
  'TtLbNtAsstsFndBlnc_EOYAmt': '3306001380'},
 'part_xi': {'object_id': '201712699349301281',
  'ein': '741109643',
  'InfInSkdOPrtXIInd': 'X',
  'RcncltnRvnExpnssAmt': '269417655',
  'NtUnrlzdGnsLsssInvstAmt': '-35625569',
  'OthrChngsInNtAsstsAmt': '-41414443'},
 'part_xii': {'object_id': '201712699349301281',
  'ein': '741109643',
  'MthdOfAccntngAccrlInd': 'X',
  'AccntntCmplOrRvwInd': 'false',
  'FSAdtdInd': 'true',
  'FSAdtdBss_CnsldtdBssFnclStmtInd': 'X',
  'AdtCmmttInd': 'true',
  'FdrlGrntAdtRqrdInd': 'true',
  'FdrlGrntAdtPrfrmdInd': 'true'}}

In [233]:
part8 = parsed_990['schedule_parts']['part_viii']
part8 = pd.DataFrame(part8.items(), columns=['Variable', 'Value'])
part8

                                   Variable               Value
0                                 object_id  201712699349301281
1                                       ein           741109643
2                       InfInSkdOPrtVIIIInd                   X
3                           RltdOrgnztnsAmt            19277811
4                           GvrnmntGrntsAmt             4794351
5                        AllOthrCntrbtnsAmt             2584024
6                            TtlCntrbtnsAmt            26656186
7           TtlOthPrgrmSrvcRv_TtlRvnClmnAmt             3957898
8   TtlOthPrgrmSrvcRv_RltdOrExmptFncIncmAmt             3270942
9       TtlOthPrgrmSrvcRv_UnrltdBsnssRvnAmt              686956
..                                      ...                 ...
26            NtIncmFrmFndrsngEvt_ExclsnAmt           -11908113
27                     MscRvn_TtlRvnClmnAmt            34807984
28             MscRvn_RltdOrExmptFncIncmAmt            31306194
29                 MscRvn_UnrltdBsnssRvnAmt              173266
30                         MscRvn_ExclsnAmt             3328524
31                            OthrRvnTtlAmt            44288095
32                     TtlRvn_TtlRvnClmnAmt          2021895478
33             TtlRvn_RltdOrExmptFncIncmAmt          1986773630
34                 TtlRvn_UnrltdBsnssRvnAmt              860222
35                         TtlRvn_ExclsnAmt             7605440

[36 rows x 2 columns]

In [214]:
DEMO_MAX = 10
num_rows = 0

for row in file_rows:
    num_rows += 1
    this_object_id = row['OBJECT_ID']
    parsed_filing = xml_runner.run_filing(this_object_id)
    
    # if it somehow busted, just note it and continue
    if not parsed_filing:
        print("Skipping filing %s(filings with pre-2013 schemas are skipped)\n row details: %s" % (this_object_id, row))
        continue 
    
    # Is there a 990 there at all?
    schedule_list = parsed_filing.list_schedules()
    if 'IRS990' in schedule_list:
        
        # store the output in this dict
        outputdata = {}
        # assign some initial values from the input csv
        outputdata['period'] = row['TAX_PERIOD_x']
        outputdata['ein'] = row['EIN']
        outputdata['object_id'] = row['OBJECT_ID']
        outputdata['taxpayer_name'] = row['TAXPAYER_NAME']
        
        # some schedules can appear multiple times, but schedule j only appears once
        # so we grab the first one 
        parsed_990 = parsed_filing.get_parsed_sked('IRS990')[0] 
        # now use the table name we looked up -- that's where we find it
        try:
            # repeating groups are returned as an array of dicts
            program_service_groups = parsed_990['schedule_parts']['part_viii']
        except KeyError:
            print("No part_viii found in %s skipping" % this_object_id)
            continue
          
        # read through each program and pull out the data we want
        for program_service_group in program_service_groups:
            
            # those keys come from the headers we gave dictwriter before
            outputdata["campaigns"] = program_service_group.get('FdrtdCmpgnsAmt')
            outputdata["membership"] = program_service_group.get('MmbrshpDsAmt')
            outputdata["fundraising"] = program_service_group.get('FndrsngAmt')
            outputdata["related_orgs"] = program_service_group.get('RltdOrgnztnsAmt')
            outputdata["government_grants"] = program_service_group.get('GvrnmntGrntsAmt')  
            outputdata["all_other_contributions"] = program_service_group.get('AllOthrCntrbtnsAmt')
            outputdata["non_cash_contributions"] = program_service_group.get('NncshCntrbtnsAmt')
            outputdata["total_contributions"] = program_service_group.get('AllOthrCntrbtnsAmt')
            outputdata["program_service_rev"] = program_service_group.get('TtlOthPrgrmSrvcRv_TtlRvnClmnAmt') #this can be pulled for all columns 
            
            dw.writerow(outputdata)
        
    else:
        print("No 990 in filing %s, skipping" % this_object_id)

    # Don't run endlessly during a demo:
    if(num_rows > DEMO_MAX):
        break
    if num_rows%100==0:
        print("Processed %s filings" % num_rows)

AttributeError: 'str' object has no attribute 'get'

In [152]:
# close the outfile
outfile.close()

pd.set_option("display.max_rows", 1000)
pd.set_option('display.min_rows', 1000)

x990_atx_efilers = pd.read_csv(outfilename)
x990_atx_efilers

Empty DataFrame
Columns: [period, ein, object_id, taxpayer_name, campaigns, membership, fundraising, related_orgs, government_grants, all_other_contributions, non_cash_contributions, total_contributions, program_service_rev]
Index: []